services:
  - type: web
    name: discourse-socket-server
    runtime: node
    repo: https://github.com/Hasib2202/discourse.ai
    branch: dev
    rootDir: socket-server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
