services:
  - type: web
    name: discourse-app
    runtime: node
    repo: https://github.com/Hasib2202/discourse.ai
    branch: devUI2
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
